#!/usr/bin/with-contenv bash

# 启动subfinder查找字幕
# exec \
	s6-setuidgid abc \
	subfinder /libraries \
	-c /config/subfinder.json -m shooter zimuku
# 等待1小时再扫描
date
echo wait an hour to restart subfinder job.
sleep 60m
